import { ALLOWED_EXTENSIONS, IGNORED_DIRS, IGNORED_FILES, MAX_FILE_SIZE_BYTES } from "../constants";
import { FileNode, DirectoryNode, ProcessingStats } from "../types";

// Helper to get extension
const getExtension = (filename: string): string => {
  const parts = filename.split('.');
  return parts.length > 1 ? '.' + parts.pop()?.toLowerCase() : '';
};

export const processFiles = async (
  fileList: FileList
): Promise<{ structure: DirectoryNode; flatFiles: FileNode[]; stats: ProcessingStats }> => {
  const root: DirectoryNode = {
    path: '/',
    name: 'root',
    type: 'directory',
    children: [],
  };
  
  const flatFiles: FileNode[] = [];
  const stats: ProcessingStats = {
    totalFiles: fileList.length,
    processedFiles: 0,
    totalSize: 0,
    ignoredFiles: 0,
  };

  const filesArray = Array.from(fileList);

  for (const file of filesArray) {
    // webkitRelativePath format: "folder/subfolder/file.ext"
    const pathParts = file.webkitRelativePath.split('/');
    
    // Check for ignored directories
    if (pathParts.some(part => IGNORED_DIRS.has(part))) {
      stats.ignoredFiles++;
      continue;
    }

    // Check for ignored files
    if (IGNORED_FILES.has(file.name)) {
      stats.ignoredFiles++;
      continue;
    }

    const extension = getExtension(file.name);
    // Check extension
    if (!ALLOWED_EXTENSIONS.has(extension)) {
      stats.ignoredFiles++;
      continue;
    }

    // Process Valid File
    let content = "";
    if (file.size <= MAX_FILE_SIZE_BYTES) {
        try {
            content = await readFileContent(file);
        } catch (e) {
            console.warn(`Failed to read file ${file.name}`, e);
            content = "// [Error reading file]";
        }
    } else {
        content = `// [File too large: ${file.size} bytes]`;
    }

    const fileNode: FileNode = {
      path: file.webkitRelativePath,
      name: file.name,
      size: file.size,
      extension,
      type: 'file',
      content
    };

    flatFiles.push(fileNode);
    stats.processedFiles++;
    stats.totalSize += file.size;

    // Build Tree
    let currentLevel = root;
    for (let i = 0; i < pathParts.length - 1; i++) {
      const folderName = pathParts[i];
      let folderNode = currentLevel.children.find(c => c.type === 'directory' && c.name === folderName) as DirectoryNode;
      
      if (!folderNode) {
        folderNode = {
          path: pathParts.slice(0, i + 1).join('/'),
          name: folderName,
          type: 'directory',
          children: []
        };
        currentLevel.children.push(folderNode);
      }
      currentLevel = folderNode;
    }
    currentLevel.children.push(fileNode);
  }

  return { structure: root, flatFiles, stats };
};

const readFileContent = (file: File): Promise<string> => {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.onload = (e) => resolve(e.target?.result as string);
    reader.onerror = (e) => reject(e);
    reader.readAsText(file);
  });
};

export const generatePackFile = (files: FileNode[]): string => {
    let output = `# CONTEXTE DU PROJET: SYMBIΩN MULTIVERSE LAB\n`;
    output += `# Generated by Symbion Code Nexus\n\n`;

    for (const file of files) {
        output += `\n${'='.repeat(50)}\n`;
        output += `FILE: ${file.path}\n`;
        output += `${'='.repeat(50)}\n\n`;
        output += file.content + "\n";
    }
    return output;
};
